<?php if(!defined('APPLICATION')) die();
// DO NOT EDIT THIS FILE
// All of the settings defined here can be overridden in the /conf/config.php file.

$Configuration['Candy']['Installed'] = False;
$Configuration['Candy']['Modules']['BreadCrumbsAssetTarget'] = False;
$Configuration['Candy']['Modules']['BreadCrumbsLastCrumbLinked'] = False;
$Configuration['Candy']['RootSectionID'] = False;
$Configuration['Candy']['Pages']['SideMenuType'] = 'Ajar';
//$Configuration['Candy']['Content']['XXX'] = '';
